Repository ummahusla/react-simple-card, pull requests merged in 2019-10, with the labels that each got.

#36 Fixed issue with incorrect border
  package.json
  src/components/CardHeader/styles.scss
Labels: bug, hacktoberfest

#37 Version bump
  package.json
Labels: enhancement, hacktoberfest

#38 Improve unit test coverage improvement
  package.json
  src/components/Card/index.tsx
  src/components/ImageHeader/__snapshots__/index.spec.tsx.snap
  src/components/ImageHeader/index.spec.tsx
  src/components/ImageHeader/index.tsx
Labels: enhancement, hacktoberfest

#39 Added examples section
  README.md
Labels: examples, hacktoberfest

#41 Bring test coverage to 100%
  src/components/ImageHeader/__snapshots__/index.spec.tsx.snap
  src/components/ImageHeader/index.spec.tsx
Labels: hacktoberfest

#40 Fix typing of style props
  src/components/Card/index.tsx
  src/components/CardBody/index.tsx
  src/components/CardFooter/index.tsx
  src/components/CardHeader/index.tsx
  src/components/ImageHeader/index.tsx
Labels: hacktoberfest
